---
- name: Restic list snapshots
  ansible.builtin.shell: restic snapshots
  # ansible.builtin.shell: restic restore $SNAPSHOT_ID --target /tmp/restore-work
  # See https://restic.readthedocs.io/en/latest/050_restore.html
  environment: 
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    RESTIC_REPOSITORY: "{{ RESTIC_REPOSITORY }}"
    RESTIC_PASSWORD: "{{ RESTIC_PASSWORD }}"
  register: results
  async: 10000
  poll: 60

- debug:
    msg: "{{ results }}.stdout_lines"

